/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
const Staff = React.memo(function Staff(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF('/models/sundae-v1.glb')
  const modelRef = useRef<THREE.Group>(null)

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.007
      // modelRef.current.rotation.x += 0.0002
    }
  })

  return (
    // <group
    //   {...props}
    //   dispose={null}
    //   scale={[3, 3, 3]}
    //   position={[0, -2, 0]}
    //   ref={modelRef}
    // >
    //   <mesh
    //     castShadow
    //     receiveShadow
    //     geometry={(nodes.Wizard_Staff3_Wizard_Staff3_0 as THREE.Mesh).geometry}
    //     material={materials.Wizard_Staff3}
    //     position={[-0.041, 0.983, 0.768]}
    //     rotation={[0, Math.PI / 2, 0]}
    //     scale={0.04}
    //   />
    //   <mesh
    //     castShadow
    //     receiveShadow
    //     geometry={
    //       (nodes.Wizard_Staff3_Wizard_Staff3_0_1 as THREE.Mesh).geometry
    //     }
    //     material={materials.Wizard_Staff3}
    //     position={[-0.041, 0.983, 0.768]}
    //     rotation={[0, Math.PI / 2, 0]}
    //     scale={0.04}
    //   />
    //   <mesh
    //     castShadow
    //     receiveShadow
    //     geometry={
    //       (nodes.Wizard_Staff3_Wizard_Staff3_0_2 as THREE.Mesh).geometry
    //     }
    //     material={materials.Wizard_Staff3}
    //     position={[-0.041, 0.983, 0.768]}
    //     rotation={[0, Math.PI / 2, 0]}
    //     scale={0.04}
    //   />
    //   <mesh
    //     castShadow
    //     receiveShadow
    //     geometry={
    //       (nodes.Wizard_Staff3_Wizard_Staff3_0_3 as THREE.Mesh).geometry
    //     }
    //     material={materials.Wizard_Staff3}
    //     position={[-0.041, 0.983, 0.768]}
    //     rotation={[0, Math.PI / 2, 0]}
    //     scale={0.04}
    //   />
    //   <mesh
    //     castShadow
    //     receiveShadow
    //     geometry={(nodes.Wizard_Staff2_Wizard_Staff2_0 as THREE.Mesh).geometry}
    //     material={materials.Wizard_Staff2}
    //     position={[-0.041, 0.983, 0.768]}
    //     rotation={[0, Math.PI / 2, 0]}
    //     scale={0.04}
    //   />
    // </group>
    <group {...props} rotation={[0.4, 0, 0]} dispose={null} ref={modelRef}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, -1.5, 0]}
        scale={0.015}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.972, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Glass_LP_Glass_0 as THREE.Mesh).geometry}
              material={materials.Glass}
              position={[-132.862, 0, 0]}
            />
          </group>
          <group position={[0, 149.604, 4.26]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes['Ice_LP_Ice-Cream_0'] as THREE.Mesh).geometry}
              material={materials['Ice-Cream']}
              position={[-132.454, 4.26, -149.947]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.GeoSphere003_Caramel_0 as THREE.Mesh).geometry}
            material={materials.Caramel}
            position={[61.81, -0.343, -190.963]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
})

export default Staff
useGLTF.preload('/models/sundae-v1.glb')
